# docker-compose.yml
# Configuração do Pi-hole (Brasil)
# Mais informações: https://github.com/pi-hole/docker-pi-hole/

version: "3.9"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest

    ports:
      # DNS (TCP/UDP)
      - "53:53/tcp"
      - "53:53/udp"
      # Painel Web
      - "30080:80/tcp"
      # HTTPS opcional
      #- "443:443/tcp"

    environment:
      TZ: 'America/Sao_Paulo'           # fuso horário do Brasil
      FTLCONF_webserver_api_password: 'cpqw.3725'
      FTLCONF_dns_listeningMode: 'all'  # escuta em todas as interfaces

    volumes:
      # Pastas locais do host → dentro do container
      - /etc/pihole/etc-pihole:/etc/pihole
      - /etc/pihole/etc-dnsmasq.d:/etc/dnsmasq.d

    cap_add:
      - NET_ADMIN   # necessário se quiser usar DHCP
      - SYS_TIME
      - SYS_NICE

    restart: unless-stopped
