version: "3.9"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped

    ports:
      # DNS (TCP/UDP)
      - "53:53/tcp"
      - "53:53/udp"
      # Interface web
      - "30080:80/tcp"
      # HTTPS opcional
      #- "443:443/tcp"

    environment:
      TZ: 'America/Sao_Paulo'
      WEBPASSWORD: 'cpqw.3725'           # senha da web
      DNSMASQ_LISTENING: 'all'

    volumes:
      # Pastas locais do host
      - /etc/pihole/etc-pihole:/etc/pihole
      - /etc/pihole/etc-dnsmasq.d:/etc/dnsmasq.d

    cap_add:
      - NET_ADMIN   # necessário se usar DHCP
      - SYS_TIME
      - SYS_NICE
