version: "3.9"

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped

    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "30080:80/tcp"

    environment:
      TZ: "America/Sao_Paulo"
      WEBPASSWORD: "cpqw.3725"
      DNSMASQ_LISTENING: "all"

    volumes:
      - /etc/pihole/etc-pihole:/etc/pihole
      - /etc/pihole/etc-dnsmasq.d:/etc/dnsmasq.d

    deploy:
      replicas: 1
      restart_policy:
        condition: any

    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
